### PR TITLE
Make `client.New` accept functional config opts

### PR DESCRIPTION
**Pull request by brandonwestcott**
I started to add a "community.GetDefault" type method as we had discussed today, but then I thought, "oh look, another long bespoke `New` method with arbitrary positional args".  That prompted the refactor below and I may have went a bit overboard, but I also think its really great.

This makes the tupelo-go-sdk `Client` accept functional options to generate a `Config` for initializing the client. This helps in setting reasonable defaults and also adds some nice named options like `WithNamedNotaryGroup("gossip4")` or `WithMemoryStorage()`.  I did keep the `client.New` method backward compatible with its existing positional args, but in the future "v2" pkg we should deprecate that. 

Opening this as a draft to get feedback before going through the effort of adding tests specifically for this, as well as a refactor for a "StartHook" that will move the `WaitForBootstrap` into `Client.Start()` instead of inside the options init.

### CODE REVIEW

**Review by cap10morgan — APPROVED** [review]
I like it!

**Comment by brandonwestcott** [comment]
@cap10morgan i've added a few more changes since the draft and last review, would you mind looking over again

**Comment by cap10morgan** [comment]
Looks even better!

**Review by cap10morgan — APPROVED** [review]
📈

**Pull request merged**
